### ISSUE TITLE
Remove dependencies to `cli` from `runner`

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/engine#30]
Nitpick: I'm not sure about this dependency.

`runner/internal/...` depends on `internal/cli/...`.

Yet `internal/cli` depends on `runner`.

It is ok because it **is** different packages. Still I find it strange because as `ansi` is nested in `cli`.

We may argue that it is strange that a core package (`report`) has io/visualization concerns.

Although, not deal breaker _at all_ for the pr.

_Originally posted by @moreirathomas in https://github.com/benchttp/engine/pull/16#discussion_r934006995_

**Comment by moreirathomas** [comment]
Closed by #48
